version: '3.6'

services:

  # Backend API
  rewards-service:
    container_name: rewards-api
    build: ./
    command: yarn start:database
    working_dir: /Workspace/fec-capstone/rewards
    env_file:
      - ./server/src/config/.env
    ports:
      - "3005:3005"
    environment:
      DATABASE_HOST: mysql
      MYSQL_URI: mysql://root:password@mysql:3306
      REDIS_URI: redis://redis:6380
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      - "mysql"
    healthcheck:
      test: ["CMD", "curl", "-f", "mysql://root:password@mysql:3306"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL
  mysql:
    image: mysql
    container_name: rewards-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kickstarter
      MYSQL_USER: k-user
      MYSQL_PASSWORD: k-pass
    ports:
      - "3306:3306"

  # Redis
  redis:
    image: redis
    container_name: rewards-redis
    ports:
      - "6380:6380"

