version: '2'

services:

  # Backend API
  rewards-service:
    container_name: rewards-api
    build: ./
    command: |
      yarn build
      yarn start:database
    working_dir: /app
    env_file:
      - ./server/src/config/.env
    ports:
      - "3005:3005"
    environment:
      DATABASE_HOST: mysql
      MYSQL_URI: mysql://root:password@mysql:3306docker
      REDIS_URI: redis://redis:6380
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      - "mysql"

  # MySQL
  mysql:
    image: mysql
    container_name: rewards-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kickstarter
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  # Redis
  redis:
    image: redis
    container_name: rewards-redis
    ports:
      - "6380:6380"

