version: 2
jobs:

  test_database:
    docker:
      - image: "circleci/node:12.16.3"
      - image: "mysql:8.0"
        command: [--default-authentication-plugin=mysql_native_password]
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: circle_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    workDir: ~/rewards-service

    steps:
      - checkout
      - run:
          name: Wait For Database Connection
          command: dockerize -wait tcp://$HOST:$PORT -timeout 1m
          environment:
            HOST: localhost
            PORT: 3306

      - run:
          name: Install Node Packages
          command: yarn install

      - run:
          name: Run Test Suite
          command: yarn ci:test
          environment:
            DATABASE_HOST: localhost
            PORT: 3000
            DATABASE_USER: user
            DATBASE_PASSWORD: password

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_database
