version: 2
jobs:

  inspect-server:
    docker:
      - image: "circleci/node:12.16.3"
      - image: "mysql:8.0"
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: kstart
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
      - checkout
      - run:
          name: Wait For Database Connection
          command: dockerize -wait tcp://$HOST:$PORT -timeout 1m
          environment:
            HOST: localhost
            PORT: 3306

      - run:
          name: Install Server Packages
          command: |
            cd server
            yarn install

      - run:
          name: Run Server Test Suite
          command: |
            cd server
            yarn ci:test

workflows:
  version: 2
  build_and_test:
    jobs:
      - server
