version: 2
jobs:

  inspect-server:
    docker:
      - image: "circleci/node:12.16.3"
      - image: "mysql:8.0.20"
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: kstart
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    working_directory: ~/repo

    steps:
      # Check Out Git Code
      - checkout

      # Wait For Database Connection
      - run:
          name: Wait For Database Connection
          command: dockerize -wait tcp://$HOST:$PORT -timeout 1m
          environment:
            HOST: localhost
            PORT: 3306

      # Update npm
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install Packages
      - run:
          name: Install Server Packages
          command: |
            npm install
            npm install mocha-junit-reporter nyc mocha eslint

      # Sace the dependency cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Make Report Directory
      - run: mkdir reports

      # Run Mocha
      - run:
          name: Run Mocha Test Suite
          command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha server/src/spec/**/*.js
          --recursive
            --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
          when: always

      # Run EsLint
      - run:
          name: Run ESLint
          command: |
            ./node_modules/.bin/eslint ./ --format junit --output-file ./reports/eslint/eslint.xml
          when: always

      # Run coverage report for Code Climate
      - run:
          name: Setup Code Climate Test-Reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always

      - run:
          name: Code Coverage
          command: |
            mkdir coverage
            # nyc report requires that nyc has already been run,
            # which creates the .nyc_output folder containing necessary data
            ./node_modules/.bin/nyc report --reporter=text-lcov > coverage/lcov.info
            ./cc-test-reporter after-build -t lcov
          when: always

      # Upload results
      - store_test_results:
          path: reports

      - store_artifacts:
          path: ./reports/mocha/test-results.xml

      - store_artifacts:
          path: ./reports/eslint/eslint.xml

      - store_artifacts: # upload test coverage as artifact
          path: ./coverage/lcov.info
          prefix: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - inspect-server
